### DISCUSSION TITLE
docker config file

### DISCUSSION THREAD

**Discussion by madcoda9000** [keeweb/keeweb#2207] [Q&A / Support]
Hello,

I've got keeweb running successfully using this compose:

```
name: keeweb
services:
    keeweb:
        container_name: keeweb
        ports:
            - 3080:80
        volumes:
            - /volume1/docker/keeweb/certificates:/etc/nginx/external/
        image: antelle/keeweb
```

I use a letyencrypt secured reverse proxy to access my keeweb docker. This is working as expected.

But how can i use a config.json. Using https://myurl/?config=config.json gives a "too many redirects" error.

I hope somone can point me in the right direction.
