### ISSUE TITLE
What would be docker-compose conf to make keeweb works with traefik?

### ISSUE THREAD

**Issue by fabthegreat** [keeweb/keeweb#1484]
Does someone have an example of a keeweb working configuration docker-compose section with traefik?
Thanks

**Comment by butonic** [comment]
you need to omit the ssl config in nginx to let traefik handle acme.
1. `./keeweb/keeweb.conf` for nginx that uses port 80
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /keeweb;
    index index.html;
    server_name localhost;

    server_tokens off;
    add_header X-Content-Type-Options nosniff;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

    location / {
        try_files $uri $uri/ =404;
    }
    location ~ /\. {
        deny all;
    }
}
```

2. in you docker compose.yaml mount the nginx config as a volume:
```yaml
  keeweb:
    restart: unless-stopped
    image: antelle/keeweb
    container_name: keeweb
    volumes:
      # override nginx config
      - "./keeweb/keeweb.conf:/etc/nginx/conf.d/keeweb.conf"
      # custom keeweb configuration
      #- "./keeweb/config.json:/keeweb/config.json"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:keeweb.example.org
      - traefik.http.routers.kw.entrypoints=https
      - traefik.http.routers.kw.rule=Host(`keeweb.example.org`)
      - traefik.http.routers.kw.tls.certresolver=myresolver
```

I hope this gives you a hint.
