### ISSUE TITLE
need the command "--no-sandbox" for execute

### ISSUE THREAD

**Issue by jw-programmer** [keeweb/keeweb#2015]
In linux, pop-os 22.04, when I click on the icon to run, nothing happens. Debugging the error, running the software through the console, for the software to start, this command needs to be executed.
`keeweb --no-sandbox`

Without the flag, this is the error in the console. the screen does not return any feedback:
`[9907:0505/222924.356522:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

**Comment by jivarson** [comment]
Are you running in a vm?
Also had issues in Ubuntu 22.04 while running keeweb. different error though but still gfx-related.
I got away by appending --no-gpu or something, but in the end I had to disable Wayland since Autotype didn't work anyway.

For that you edit /etc/gdm3/custom.conf and uncomment the line
`#WaylandEnable=false
`

**Comment by jw-programmer** [comment]
No, no VM. From what I've seen, the error that occurred has to do with that.  But for me, it solved by running the command with the no-sandbox flag through the terminal.

**Comment by Evergreenn** [comment]
Same error here. Maybe related to [this](https://github.com/keeweb/keeweb/issues/1975) ?

**Comment by jivarson** [comment]
> Have the same issue in POP OS, not in VM. It's still an on going issue, and the disable GPU flag doesn't help. Only the Sandbox one does which is concerning to use on a password storing application.

Have you tried to disable Wayland as I mentioned above?

**Comment by jw-programmer** [comment]
As far as I know, this version of pop os doesn't use wayland. But in the end, it didn't have to. Started working again. Unfortunately I don't know what I did differently.

**Comment by damianmoore** [comment]
I'm also finding that I have to disable the sandbox when trying to run the snap version on Ubuntu 22.04. This is how I have to run it:
`/snap/keeweb/x1/app/keeweb --no-sandbox`

**Comment by damianmoore** [comment]
I guess it could be a bug/incompatibility with the version of Electron: https://github.com/electron/electron/issues/16631

Otherwise it might be solvable by tweaking the `plugs` in `snap.yml` but I can't find the file in the repo. Maybe it's created in the GitHub Action.

`meta/snap.yml` from snap package:
```                                                                                                                         
name: keeweb
version: 1.18.7
summary: keeweb
description: Free cross-platform password manager compatible with KeePass
apps:
  keeweb:
    command: command.sh
    plugs:
    - desktop
    - desktop-legacy
    - home
    - x11
    - wayland
    - unity7
    - browser-support
    - network
    - gsettings
    - audio-playback
    - pulseaudio
    - opengl
    environment:
      DISABLE_WAYLAND: '1'
      TMPDIR: $XDG_RUNTIME_DIR
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
architectures:
- amd64
base: core18
confinement: strict
grade: stable
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
title: keeweb
```

There's a `browser-sandbox` plug as well as `browser-support` which could be useful but I don't have a build environment to try right now.
