### ISSUE TITLE
keeweb limits the use of subfolders!

### ISSUE THREAD

**Issue by collector-ynh** [keeweb/keeweb#2119]
Hello, I noticed that it was not possible to create subfolders on more than 5 levels.  I would like to know how to deactivate this limitation, because it is very important for me to use subfolders on more than 5 levels in keeweb.

 Thank you in advance for your assistance !

**Comment by Aetherinox** [comment]
Adding a note here
![DonL9A7kpc](https://github.com/keeweb/keeweb/assets/118329232/584f704c-6785-41da-8ed9-1b7630739dde)

**Comment by Aetherinox** [comment]
Just an update here.

Are you referring to the screenshot above? It appears there's no hard limit as to the actual number of sub folders you can have. The styling is really just CSS.

Each subfolder increases the left padding by 1em

```css
.menu__item > .menu__item > .menu__item > .menu__item > & {
    padding-left: $base-padding-h * 4;
}
```

I added two more, and allowed for the side panel to be enlarged a bit more.

![mUB1HSwGTw](https://github.com/keeweb/keeweb/assets/118329232/a1dfc4e1-f84a-4e72-962e-e2103b91d988)
