### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#611]
Branch https://github.com/EnricoMonese/keeweb/tree/theming

Moved appearance settings in new Theming section in app settings.

The plan is to make a theme builder with export-import support through json theme files (similar to export api for settings).
Suggestions for a color picker are welcome.
The plugin-theme should be removed as themes will be independent. Plugins can still be used for theming purposes, they just wont be applied as themes like they are now.

**Comment by antelle** [comment]
Themes will be installed only as plugins. We don't need a separate section for this.

**Comment by EnricoMonese** [comment]
So the theme builder ships with Keeweb and exports themes as plugins, is this right?

**Comment by antelle** [comment]
No, it won't be a part of core product, so it won't ship with keeweb, because creating a plugin or theme is not something regular user needs.
But we already support CSS in plugins. Creating a theme should be as simple as generating proper css for it. We can begin with (ab)using existing scss and extracting styles generated for theme. Later, I'm planning to get rid of static css generation (aka `th`) and replace it with color classes, which will be included in theme, as well as other css, if required by design.

**Comment by antelle** [comment]
So, the basic migration plan:
1. replace `@include th { color: theme-color(); }` with `var(--theme-color)`
2. separate borders and other stuff from themes, assign theme variables to `body.theme`
3. create a generator

Hm, step 1 can be done with simple find'n'replace, step2 is also not that hard, because we have about 30 styles total. I'll think about implementing it in the upcoming version.

**Comment by EnricoMonese** [comment]
There could be some general options for colors of text and things. Sections already have usable names like _app__menu_, each section could then have options for color of buttons, labels, input fields etc. that are inside them. If not defined the general colors would be used.

**Comment by EnricoMonese** [comment]
Also if theming uses variables, the plugin-theme could just define the variables, is this how it works? Haven't really used css variables until recently

**Comment by antelle** [comment]
> each section could then have options for color of buttons, labels

CSS variables is easier to implement and support. Browsers without CSS variables will support only default theme, and it won't be possible to change it. It's now only Edge 14, which is decreasing as Edge 15 is already released, but still has 50% of total Edge traffic.
> Also if theming uses variables, the plugin-theme could just define the variables, is this how it works? 

Example of plugin css with variables:
```css
.th-dark-brown {
  /* basic theme colors */
  --background-color: #342F2E;
  --medium-color: #FED9D8;
  --text-color: #FFEAE9;
  --action-color: #2C9957;
  --error-color: #FD6D67;
  /* other colors created by theme generator, about 20 colors */
  /* but it's still possible to customize them */
  --base-border-color: ...;
  --accent-border-color: ...;
}
```
